### ISSUE TITLE
Manteiner

### ISSUE THREAD

**Issue by mirkobrombin** [chrisnharvey/CodeIgniter-PDF-Generator-Library#1]
I'm interested to become the maintainer of this library. 
- Mirko

**Comment by chrisnharvey** [comment]
Great!

I'm happy to hand this project over to you. The only thing I'd ask is if my name could be left in as credit to the original author?

If so, then I'm happy to transfer this project over to you. 

Do you have any ideas on how you could improve it?

Cheers,

Chris

**Comment by mirkobrombin** [comment]
Hello, thank you for your response.
I'm using this library in some of my projects and at the time I think about some improvements of code caching documents.

**Comment by redelement** [comment]
Not sure if this transfer ever happened. I'd be more than happy to maintain this project if not.
